log_level: DEBUG

server:
  port: ":8080"
  host: "0.0.0.0"  
  # host: "localhost"  

postgres_db:
  user: postgres
  pass: password
  host: db          
  # host: localhost
  port: 5432
  name: effective_mobile_db
  max_attempts: 5