definitions:
  handler.ApiErrResponse:
    properties:
      error:
        type: string
      status:
        description: '"ok" / "error"'
        type: string
    type: object
  handler.ApiOkResponse:
    properties:
      data: {}
      status:
        description: '"ok" / "error"'
        type: string
    type: object
  models.SubscriptionRequest:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  models.SubscriptionResponse:
    properties:
      end_date:
        type: string
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /subscription:
    post:
      consumes:
      - application/json
      description: Добавляет новую подписку для пользователя
      parameters:
      - description: Данные новой подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ID созданной подписки
          schema:
            $ref: '#/definitions/handler.ApiOkResponse'
        "400":
          description: Неверный JSON или ошибка валидации
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
      summary: Создать подписку
      tags:
      - subscriptions
  /subscription/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет подписку по ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Неверный ID или ошибка удаления
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
      summary: Удалить подписку
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает информацию о подписке по её идентификатору
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Данные подписки
          schema:
            $ref: '#/definitions/models.SubscriptionResponse'
        "400":
          description: Неверный формат ID
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
      summary: Получить подписку по ID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет существующую подписку по ID
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      - description: Данные для обновления
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            type: string
        "400":
          description: Неверный JSON, ошибка валидации или ID
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
      summary: Обновить подписку
      tags:
      - subscriptions
  /subscription/list/{uuid}:
    get:
      consumes:
      - application/json
      description: Возвращает список подписок по UUID пользователя
      parameters:
      - description: UUID пользователя
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список подписок
          schema:
            items:
              $ref: '#/definitions/models.SubscriptionResponse'
            type: array
        "400":
          description: Неверный формат UUID
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "404":
          description: Подписки не найдены
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
      summary: Получить список подписок пользователя
      tags:
      - subscriptions
  /subscription/stats:
    get:
      consumes:
      - application/json
      description: Возвращает сумму стоимости подписок пользователя за указанный период.
        Можно указать сервис для фильтрации.
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        required: true
        type: string
      - description: Название сервиса (необязательный)
        in: query
        name: service_name
        type: string
      - description: Начало периода (формат ММ-ГГГГ)
        in: query
        name: from
        required: true
        type: string
      - description: Конец периода (формат ММ-ГГГГ)
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Общая стоимость
          schema:
            $ref: '#/definitions/handler.ApiOkResponse'
        "400":
          description: Неверные параметры запроса
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
        "500":
          description: Ошибка сервера
          schema:
            $ref: '#/definitions/handler.ApiErrResponse'
      summary: Получить общую стоимость подписок
      tags:
      - subscriptions
swagger: "2.0"
